# Production Docker Compose configuration for ForkSpy

services:
  # ForkSpy Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forkspy-app-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3001}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3001}
    ports:
      - "3001:3000"
    networks:
      - forkspy-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx Reverse Proxy (optional for production)
  nginx:
    image: nginx:alpine
    container_name: forkspy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy
    networks:
      - forkspy-network
    profiles:
      - proxy

networks:
  forkspy-network:
    driver: bridge
