# Testing Docker Compose configuration for ForkSpy

services:
  # Test Runner Service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: forkspy-test-runner
    environment:
      - NODE_ENV=test
      - MONGO_URI=${MONGO_URI}
      - GITHUB_ID=test_github_id
      - GITHUB_SECRET=test_github_secret
      - NEXTAUTH_SECRET=test_secret_for_testing_only
      - NEXTAUTH_URL=http://localhost:3000
      - RESEND_API_KEY=test_resend_key
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    networks:
      - forkspy-test-network
    command: ["npm", "run", "test:coverage"]

  # Watch Mode Test Runner
  test-watch:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: forkspy-test-watch
    environment:
      - NODE_ENV=test
      - MONGO_URI=${MONGO_URI}
      - GITHUB_ID=test_github_id
      - GITHUB_SECRET=test_github_secret
      - NEXTAUTH_SECRET=test_secret_for_testing_only
      - NEXTAUTH_URL=http://localhost:3000
      - RESEND_API_KEY=test_resend_key
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - forkspy-test-network
    profiles:
      - watch
    command: ["npm", "run", "test:watch"]
    stdin_open: true
    tty: true

networks:
  forkspy-test-network:
    driver: bridge
